export type CardType = "archetipo" | "ricordo" | "maschera" | "oblio" | "sogno" | "eco";
export type Rarity = "comune" | "rara" | "epica" | "leggendaria";
export type TerritoryId = "memoria" | "trauma" | "sogno";

export type CardTrait =
  | "immobile" // Ignores buffs/weakens
  | "growth" // Gains power every turn
  | "executioner" // Executes weakest enemy if condition met
  | "resetter" // Resets global buffs on play
  | "synergy_buff" // Gains power from others of same type
  | "loner" // Bonus power if alone in territory
  | "protector" // Protects neighbors from debuffs
  | "oppressive" // Reduces enemy power on play
  | "dynamic_heal"; // Heal amount based on board state

export type CardEffect =
  | { kind: "draw"; amount: number }
  | { kind: "buff_self"; amount: number; target?: "global" | "local" }
  | { kind: "weaken_enemy"; amount: number; target?: "global" | "local" }
  | { kind: "heal"; amount: number }
  | { kind: "add_intrusive"; amount: number }
  | { kind: "trauma_enemy"; amount: number }
  | { kind: "steal_lucidity"; amount: number }
  | { kind: "none" };

export interface CardDef {
  id: string;
  name: string;
  type: CardType;
  cost: number;
  power: number;
  rarity: Rarity;
  text: string;
  flavor?: string;
  effect: CardEffect;
  traits?: CardTrait[];
  unlockLevel?: number; // Minimum level to find/unlock this card
  art: string; // path under /cards
}

export const CARDS: CardDef[] = [
  // --- FAZIONE: ARCHETIPO (VIOLA - PSICHE PROFONDA) ---
  {
    id: "v1_ambizione",
    name: "Ambizione",
    type: "archetipo",
    cost: 5,
    power: 8,
    rarity: "leggendaria",
    text: "Attira a sé le risorse vicine, potenziando la propria energia per ogni frammento stellare raccolto.",
    flavor: "Voglio tutto, anche se il prezzo è la mia anima.",
    effect: { kind: "buff_self", amount: 2, target: "local" },
    unlockLevel: 10,
    art: "/cards/ambizione.png?v=3",
  },
  {
    id: "v2_ossessione",
    name: "Ossessione",
    type: "archetipo",
    cost: 4,
    power: 6,
    rarity: "epica",
    text: "Rivela le intenzioni nascoste dell'avversario, distorcendo la sua percezione della realtà.",
    flavor: "Un pensiero che si nutre di te finché non resta altro.",
    effect: { kind: "weaken_enemy", amount: 1, target: "global" },
    traits: ["synergy_buff"],
    unlockLevel: 5,
    art: "/cards/ossessione.png?v=3",
  },
  {
    id: "v3_nostalgia",
    name: "Nostalgia",
    type: "archetipo",
    cost: 2,
    power: 3,
    rarity: "rara",
    text: "Evoca un ricordo dal passato, permettendo di recuperare una risorsa perduta nel vuoto.",
    flavor: "Un passato che brilla più del presente.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 3,
    art: "/cards/nostalgia.png?v=3",
  },
  {
    id: "v4_apatia",
    name: "Apatia",
    type: "archetipo",
    cost: 3,
    power: 6,
    rarity: "comune",
    text: "Immobilizza una minaccia nemica, rendendola inerte come cenere sotto un sole morente.",
    flavor: "Nulla fa più male, nulla fa più bene.",
    effect: { kind: "none" },
    traits: ["immobile"],
    unlockLevel: 1,
    art: "/cards/apatia.png?v=3",
  },
  {
    id: "v5_follia",
    name: "Follia",
    type: "archetipo",
    cost: 6,
    power: 10,
    rarity: "leggendaria",
    text: "Scatena un vortice di caos che spezza le difese nemiche attraverso geometrie impossibili.",
    flavor: "La verità è un cerchio che non si chiude mai.",
    effect: { kind: "buff_self", amount: 3, target: "local" },
    unlockLevel: 10,
    art: "/cards/follia.png?v=3",
  },
  {
    id: "v6_empatia",
    name: "Empatia",
    type: "archetipo",
    cost: 3,
    power: 3,
    rarity: "rara",
    text: "Crea un riverbero emotivo che guarisce la tua coscienza per ogni carta Archetipo in gioco.",
    flavor: "Sento il tuo peso come se fosse il mio.",
    effect: { kind: "heal", amount: 2 },
    traits: ["dynamic_heal"],
    unlockLevel: 3,
    art: "/cards/empatia.png?v=3",
  },
  {
    id: "v7_rancore",
    name: "Rancore",
    type: "archetipo",
    cost: 4,
    power: 5,
    rarity: "rara",
    text: "Infligge un'eco di dolore che riduce il Potere di tutte le carte nemiche in questo territorio.",
    flavor: "Un fuoco che brucia senza mai spegnersi.",
    effect: { kind: "weaken_enemy", amount: 1, target: "local" },
    unlockLevel: 3,
    art: "/cards/rancore.png?v=3",
  },
  {
    id: "v8_solitudine",
    name: "Solitudine",
    type: "archetipo",
    cost: 2,
    power: 4,
    rarity: "comune",
    text: "Guadagna +3 Potere se è l'unica tua carta in questo territorio.",
    flavor: "Un'isola in un mare di stelle morte.",
    effect: { kind: "none" },
    traits: ["loner"],
    unlockLevel: 1,
    art: "/cards/solitudine.png?v=3",
  },
  {
    id: "v9_coraggio",
    name: "Coraggio",
    type: "archetipo",
    cost: 3,
    power: 4,
    rarity: "comune",
    text: "Protegge le tue carte adiacenti dalla riduzione di Potere.",
    flavor: "L'ultimo baluardo prima del buio assoluto.",
    effect: { kind: "none" },
    traits: ["protector"],
    unlockLevel: 1,
    art: "/cards/coraggio.png?v=3",
  },
  {
    id: "v10_armonia",
    name: "Armonia",
    type: "archetipo",
    cost: 4,
    power: 6,
    rarity: "leggendaria",
    text: "Sincronizza le tue risorse: pesca 1 carta.",
    flavor: "Il silenzio perfetto tra due battiti del cuore.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 10,
    art: "/cards/armonia.png?v=3",
  },

  // --- FAZIONE: RICORDO (ORO - FRAMMENTI SACRI) ---
  {
    id: "o1_chiave_antica",
    name: "Chiave Antica",
    type: "ricordo",
    cost: 1,
    power: 1,
    rarity: "comune",
    text: "Pesca 1 carta.",
    flavor: "Apre porte che avrei dovuto lasciare chiuse.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 1,
    art: "/cards/chiave_antica.png?v=3",
  },
  {
    id: "o2_bosco_sacro",
    name: "Bosco Sacro",
    type: "ricordo",
    cost: 4,
    power: 6,
    rarity: "epica",
    text: "+1 Potere globale.",
    flavor: "Tutto era magico, finché non abbiamo iniziato a capire.",
    effect: { kind: "buff_self", amount: 1, target: "global" },
    unlockLevel: 5,
    art: "/cards/bosco_sacro.png?v=3",
  },
  {
    id: "o3_giocattolo",
    name: "Giocattolo Rotto",
    type: "ricordo",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Infligge 10% Trauma all'avversario. L'innocenza spezzata non si ripara.",
    flavor: "Le promesse infrante non si possono riparare.",
    effect: { kind: "trauma_enemy", amount: 10 },
    unlockLevel: 1,
    art: "/cards/giocattolo_rotto.png?v=3",
  },
  {
    id: "o4_lettera",
    name: "Lettera Sigillata",
    type: "ricordo",
    cost: 2,
    power: 2,
    rarity: "rara",
    text: "Pesca 2 carte.",
    flavor: "Certe verità dovrebbero restare nel buio.",
    effect: { kind: "draw", amount: 2 },
    unlockLevel: 3,
    art: "/cards/lettera_sigillata.png?v=3",
  },
  {
    id: "o5_cenere",
    name: "Cenere e Stelle",
    type: "ricordo",
    cost: 6,
    power: 9,
    rarity: "leggendaria",
    text: "+2 Potere globale.",
    flavor: "Siamo polvere di stelle destinata a tornare cenere.",
    effect: { kind: "buff_self", amount: 2, target: "global" },
    traits: ["synergy_buff"],
    unlockLevel: 10,
    art: "/cards/cenere_e_stelle.png?v=3",
  },
  {
    id: "o6_giardino",
    name: "Giardino Segreto",
    type: "ricordo",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Cura 2 HP.",
    flavor: "Un luogo dove il tempo non osa entrare.",
    effect: { kind: "heal", amount: 2 },
    unlockLevel: 3,
    art: "/cards/giardino_segreto.png?v=3",
  },
  {
    id: "o7_primo_volo",
    name: "Primo Volo",
    type: "ricordo",
    cost: 3,
    power: 5,
    rarity: "rara",
    text: "Aura +2 Potere alle carte alleate in questa Lane.",
    flavor: "Prima che la gravità diventasse una legge crudele.",
    effect: { kind: "buff_self", amount: 2, target: "local" },
    unlockLevel: 3,
    art: "/cards/primo_volo.png?v=3",
  },
  {
    id: "o8_tempesta",
    name: "Tempesta",
    type: "ricordo",
    cost: 5,
    power: 7,
    rarity: "epica",
    text: "Pesca 1 carta.",
    flavor: "Il cielo urlava la nostra rabbia repressa.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 5,
    art: "/cards/tempesta_ricordo.png?v=3",
  },
  {
    id: "o9_nebbia",
    name: "Nebbia d'Oro",
    type: "ricordo",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Nella nebbia del passato, trovi qualcosa di dimenticato. Pesca 1 carta.",
    flavor: "Il passato si confonde con la bellezza del trauma.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 1,
    art: "/cards/nebbia_oro.png?v=3",
  },
  {
    id: "o10_anello",
    name: "L'Anello Spezzato",
    type: "ricordo",
    cost: 2,
    power: 4,
    rarity: "rara",
    text: "Il legame infranto drena 1 Lucidità dall'avversario.",
    flavor: "Un cerchio che non protegge più nulla.",
    effect: { kind: "steal_lucidity", amount: 1 },
    unlockLevel: 3,
    art: "/cards/anello_spezzato.png?v=3",
  },

  // --- FAZIONE: MASCHERA (CREMISI - DIFESA SOCIALE) ---
  {
    id: "c1_giullare",
    name: "Il Giullare",
    type: "maschera",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "La maschera del sorriso infligge 5% Trauma all'avversario.",
    flavor: "Il pubblico non deve mai vedere la lacrima sotto il trucco.",
    effect: { kind: "trauma_enemy", amount: 5 },
    unlockLevel: 1,
    art: "/cards/giullare.png?v=3",
  },
  {
    id: "c2_re_caduto",
    name: "Il Re Caduto",
    type: "maschera",
    cost: 5,
    power: 7,
    rarity: "epica",
    text: "Presenza opprimente.",
    flavor: "Una corona di spine pesa più di una d'oro.",
    effect: { kind: "none" },
    traits: ["oppressive"],
    unlockLevel: 5,
    art: "/cards/re_caduto.png?v=3",
  },
  {
    id: "c3_vittima",
    name: "La Vittima",
    type: "maschera",
    cost: 1,
    power: 2,
    rarity: "comune",
    text: "Il suo dolore drena 1 Lucidità dall'avversario.",
    flavor: "Il dolore è l'unica cosa che mi fa sentire vivo.",
    effect: { kind: "steal_lucidity", amount: 1 },
    unlockLevel: 1,
    art: "/cards/vittima.png?v=3",
  },
  {
    id: "c4_attore",
    name: "L'Attore",
    type: "maschera",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Aura -1 Potere ai nemici in questa Lane.",
    flavor: "Posso essere chiunque, tranne me stesso.",
    effect: { kind: "weaken_enemy", amount: 1, target: "local" },
    unlockLevel: 3,
    art: "/cards/attore.png?v=3",
  },
  {
    id: "c5_martire",
    name: "Il Martire",
    type: "maschera",
    cost: 4,
    power: 5,
    rarity: "rara",
    text: "Cura 2 HP.",
    flavor: "Il mio sangue nutre la speranza degli altri.",
    effect: { kind: "heal", amount: 2 },
    unlockLevel: 3,
    art: "/cards/martire.png?v=3",
  },
  {
    id: "c6_giudice",
    name: "Il Giudice",
    type: "maschera",
    cost: 4,
    power: 6,
    rarity: "epica",
    text: "Equilibrio.",
    flavor: "La giustizia è una bilancia che pende sempre dal lato del vuoto.",
    effect: { kind: "none" },
    unlockLevel: 5,
    art: "/cards/giudice.png?v=3",
  },
  {
    id: "c7_bambino",
    name: "Bambino Eterno",
    type: "maschera",
    cost: 2,
    power: 2,
    rarity: "rara",
    text: "Pesca 1 carta.",
    flavor: "L'innocenza è una maschera che non invecchia mai.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 3,
    art: "/cards/bambino_eterno.png?v=3",
  },
  {
    id: "c8_eremita",
    name: "L'Eremita",
    type: "maschera",
    cost: 3,
    power: 5,
    rarity: "comune",
    text: "Isolamento.",
    flavor: "Nel silenzio della maschera, trovo la mia verità.",
    effect: { kind: "none" },
    traits: ["loner"],
    unlockLevel: 1,
    art: "/cards/eremita.png?v=3",
  },
  {
    id: "c9_mostro",
    name: "Il Mostro",
    type: "maschera",
    cost: 5,
    power: 8,
    rarity: "rara",
    text: "Inquina la mente avversaria con 1 Pensiero Intrusivo.",
    flavor: "Tutti abbiamo un mostro che indossa un volto umano.",
    effect: { kind: "add_intrusive", amount: 1 },
    traits: ["oppressive"],
    unlockLevel: 3,
    art: "/cards/mostro.png?v=3",
  },
  {
    id: "c10_boia",
    name: "Il Boia",
    type: "maschera",
    cost: 6,
    power: 7,
    rarity: "leggendaria",
    text: "Taglia il potere -3.",
    flavor: "La fine del viaggio è solo un altro colpo di scure.",
    effect: { kind: "weaken_enemy", amount: 3, target: "local" },
    traits: ["executioner"],
    unlockLevel: 10,
    art: "/cards/boia.png?v=3",
  },
  {
    id: "c11_ombra_riflessa",
    name: "L'Ombra Riflessa",
    type: "maschera",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Proietta le colpe: -1 Potere a un nemico.",
    flavor: "Non guardi me, guardi ciò che odi di te stesso.",
    effect: { kind: "weaken_enemy", amount: 1, target: "local" },
    unlockLevel: 3,
    art: "/cards/ombra_riflessa.png?v=3",
  },
  {
    id: "c12_traditore",
    name: "Il Traditore Latente",
    type: "maschera",
    cost: 4,
    power: 7,
    rarity: "epica",
    text: "Aggiunge 1 Pensiero Intrusivo alla mano nemica.",
    flavor: "La mano che ti nutre è la stessa che stringe il cappio.",
    effect: { kind: "add_intrusive", amount: 1 },
    traits: ["oppressive"],
    unlockLevel: 5,
    art: "/cards/traditore_latente.png?v=3",
  },
  {
    id: "c13_bestia",
    name: "La Bestia Repressa",
    type: "maschera",
    cost: 6,
    power: 10,
    rarity: "leggendaria",
    text: "Istinto inarrestabile.",
    flavor: "Le catene della ragione sono fatte di vetro sottile.",
    effect: { kind: "none" },
    traits: ["growth"],
    unlockLevel: 10,
    art: "/cards/bestia_repressa.png?v=3",
  },
  {
    id: "c14_corruttore",
    name: "Il Corruttore Silenzioso",
    type: "maschera",
    cost: 3,
    power: 5,
    rarity: "rara",
    text: "-1 Potere ai nemici qui.",
    flavor: "Ogni compromesso è un mattone nella tua prigione.",
    effect: { kind: "weaken_enemy", amount: 1, target: "local" },
    unlockLevel: 3,
    art: "/cards/corruttore_silenzioso.png?v=3",
  },
  {
    id: "c15_altro_me",
    name: "L'Altro Me",
    type: "maschera",
    cost: 5,
    power: 6,
    rarity: "epica",
    text: "+2 Potere per Maschera.",
    flavor: "Siamo due facce di una moneta che non ha mai toccato terra.",
    effect: { kind: "buff_self", amount: 2, target: "local" },
    traits: ["synergy_buff"],
    unlockLevel: 5,
    art: "/cards/altro_me.png?v=3",
  },
  {
    id: "c16_adulatore",
    name: "L'Adulatore Oscuro",
    type: "maschera",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Falsa cortesia.",
    flavor: "Le sue lodi profumano di marciume e vecchia ambizione.",
    effect: { kind: "none" },
    unlockLevel: 1,
    art: "/cards/adulatore_oscuro.png?v=3",
  },
  {
    id: "c17_voce",
    name: "La Voce Proibita",
    type: "maschera",
    cost: 2,
    power: 2,
    rarity: "rara",
    text: "Pesca 1 carta.",
    flavor: "Urla nel vuoto quello che non osi sussurrare allo specchio.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 3,
    art: "/cards/voce_proibita.png?v=3",
  },
  {
    id: "c18_tiranno",
    name: "Il Tiranno Invisibile",
    type: "maschera",
    cost: 5,
    power: 8,
    rarity: "epica",
    text: "Dominio solitario.",
    flavor: "Governo il regno che hai giurato di non visitare mai.",
    effect: { kind: "none" },
    traits: ["loner"],
    unlockLevel: 5,
    art: "/cards/tiranno_invisibile.png?v=3",
  },
  {
    id: "c19_invidioso",
    name: "L'Invidioso",
    type: "maschera",
    cost: 1,
    power: 2,
    rarity: "comune",
    text: "-1 Potere ai nemici.",
    flavor: "Il tuo splendore è solo un'offesa alla mia oscurità.",
    effect: { kind: "none" },
    traits: ["oppressive"],
    unlockLevel: 1,
    art: "/cards/invidioso.png?v=3",
  },
  {
    id: "c20_oro_sepolto",
    name: "L'Oro Sepolto",
    type: "maschera",
    cost: 4,
    power: 4,
    rarity: "leggendaria",
    text: "+2 Potere ogni turno.",
    flavor: "C'è una luce che brilla così forte da farti paura.",
    effect: { kind: "none" },
    traits: ["growth"],
    unlockLevel: 10,
    art: "/cards/oro_sepolto.png?v=3",
  },

  // --- FAZIONE: OBLIO (BLU FREDDO - VUOTO E PERDITA) ---
  {
    id: "b1_vuoto",
    name: "Il Vuoto",
    type: "oblio",
    cost: 4,
    power: 5,
    rarity: "rara",
    text: "Annulla effetti.",
    flavor: "Non c'è nulla qui, nemmeno il dolore.",
    effect: { kind: "none" },
    traits: ["resetter"],
    unlockLevel: 3,
    art: "/cards/vuoto.png?v=3",
  },
  {
    id: "b2_silenzio",
    name: "Silenzio",
    type: "oblio",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Il silenzio assoluto drena 1 Lucidità dall'avversario.",
    flavor: "Il rumore del mondo è solo un ricordo lontano.",
    effect: { kind: "steal_lucidity", amount: 1 },
    unlockLevel: 1,
    art: "/cards/silenzio.png?v=3",
  },
  {
    id: "b3_oblio",
    name: "Oblio",
    type: "oblio",
    cost: 6,
    power: 8,
    rarity: "leggendaria",
    text: "Potere che annichilisce la memoria.",
    flavor: "Chi eri prima che il tempo ti mangiasse?",
    effect: { kind: "none" },
    unlockLevel: 10,
    art: "/cards/oblio.png?v=3",
  },
  {
    id: "b4_neve",
    name: "Neve Eterna",
    type: "oblio",
    cost: 3,
    power: 4,
    rarity: "comune",
    text: "Aura Glaciale: -1 Potere ai nemici in questa Lane.",
    flavor: "Ogni fiocco è un ricordo che si gela.",
    effect: { kind: "weaken_enemy", amount: 1, target: "local" },
    unlockLevel: 1,
    art: "/cards/neve_eterna.png?v=3",
  },
  {
    id: "b5_cenere_blu",
    name: "Cenere Blu",
    type: "oblio",
    cost: 5,
    power: 7,
    rarity: "epica",
    text: "Debuff -2.",
    flavor: "Ciò che resta dopo che la speranza si è spenta.",
    effect: { kind: "weaken_enemy", amount: 2, target: "global" },
    unlockLevel: 5,
    art: "/cards/cenere_blu.png?v=3",
  },
  {
    id: "b6_abisso",
    name: "L'Abisso",
    type: "oblio",
    cost: 6,
    power: 9,
    rarity: "leggendaria",
    text: "Potere puro.",
    flavor: "L'oscurità è l'unica casa che ci accetta sempre.",
    effect: { kind: "none" },
    unlockLevel: 10,
    art: "/cards/abisso.png?v=3",
  },
  {
    id: "b7_pioggia",
    name: "Pioggia Fredda",
    type: "oblio",
    cost: 2,
    power: 2,
    rarity: "comune",
    text: "Pesca 1 carta.",
    flavor: "Lacrime dal cielo di un mondo dimenticato.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 1,
    art: "/cards/pioggia_fredda.png?v=3",
  },
  {
    id: "b8_fantasma",
    name: "Il Fantasma",
    type: "oblio",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Lo spettro ti mostra ciò che è andato perduto. Pesca 1 carta.",
    flavor: "Un'eco che ha smesso di cercare una voce.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 3,
    art: "/cards/fantasma.png?v=3",
  },
  {
    id: "b9_rovine",
    name: "Rovine",
    type: "oblio",
    cost: 4,
    power: 6,
    rarity: "rara",
    text: "Struttura fragile.",
    flavor: "Le fondamenta della mente stanno crollando.",
    effect: { kind: "none" },
    unlockLevel: 3,
    art: "/cards/rovine.png?v=3",
  },
  {
    id: "b10_ghiaccio",
    name: "Cuore di Ghiaccio",
    type: "oblio",
    cost: 5,
    power: 6,
    rarity: "epica",
    text: "Cura 3 HP.",
    flavor: "Congela il dolore per non sentirlo più.",
    effect: { kind: "heal", amount: 3 },
    unlockLevel: 5,
    art: "/cards/cuore_ghiaccio.png?v=3",
  },

  // --- FAZIONE: SOGNO (CIANO - ILLUSIONE e SPERANZA) ---
  {
    id: "s1_miraggio",
    name: "Miraggio",
    type: "sogno",
    cost: 2,
    power: 2,
    rarity: "comune",
    text: "L'illusione ti svela ciò che cerchi. Pesca 1 carta.",
    flavor: "Bello da vedere, impossibile da toccare.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 1,
    art: "/cards/miraggio.png?v=3",
  },
  {
    id: "s2_aurora",
    name: "Aurora",
    type: "sogno",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "La luce dell'alba cura 2 HP.",
    flavor: "La promessa di un risveglio che non arriva mai.",
    effect: { kind: "heal", amount: 2 },
    unlockLevel: 3,
    art: "/cards/aurora.png?v=3",
  },
  {
    id: "s3_nuvola",
    name: "Nuvola di Sogni",
    type: "sogno",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Fluttuando: Aura +1 Potere alle carte alleate in questa Lane.",
    flavor: "Fluttuare sopra l'abisso del reale.",
    effect: { kind: "buff_self", amount: 1, target: "local" },
    unlockLevel: 1,
    art: "/cards/nuvola_sogni.png?v=3",
  },
  {
    id: "s4_visione",
    name: "Visione Eterea",
    type: "sogno",
    cost: 5,
    power: 7,
    rarity: "epica",
    text: "Pesca 2 carte.",
    flavor: "Vedere attraverso il velo del tempo.",
    effect: { kind: "draw", amount: 2 },
    unlockLevel: 5,
    art: "/cards/visione_eterea.png?v=3",
  },
  {
    id: "s5_stella",
    name: "Stella Cadente",
    type: "sogno",
    cost: 1,
    power: 1,
    rarity: "comune",
    text: "Un desiderio esaudito. Cura 2 HP.",
    flavor: "Brilla intensamente prima di spegnersi per sempre.",
    effect: { kind: "heal", amount: 2 },
    unlockLevel: 1,
    art: "/cards/stella_cadente.png?v=3",
  },
  {
    id: "s6_isole",
    name: "Isole Sospese",
    type: "sogno",
    cost: 4,
    power: 5,
    rarity: "rara",
    text: "Gravità zero.",
    flavor: "Dove il pensiero è l'unico peso consentito.",
    effect: { kind: "none" },
    unlockLevel: 3,
    art: "/cards/isole_sospese.png?v=3",
  },
  {
    id: "s7_farfalla",
    name: "Farfalla di Luce",
    type: "sogno",
    cost: 2,
    power: 3,
    rarity: "rara",
    text: "Cura 1 HP.",
    flavor: "Un battito d'ali che sposta le nuvole della mente.",
    effect: { kind: "heal", amount: 1 },
    unlockLevel: 3,
    art: "/cards/farfalla_luce.png?v=3",
  },
  {
    id: "s8_arcobaleno",
    name: "Arcobaleno Notturno",
    type: "sogno",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Speranza.",
    flavor: "Anche nel buio più profondo, i colori trovano una via.",
    effect: { kind: "none" },
    unlockLevel: 3,
    art: "/cards/arcobaleno_notturno.png?v=3",
  },
  {
    id: "s9_citta",
    name: "Città Invisibile",
    type: "sogno",
    cost: 6,
    power: 8,
    rarity: "epica",
    text: "Rifugio onirico.",
    flavor: "Costruita con i mattoni di ciò che avremmo voluto essere.",
    effect: { kind: "none" },
    unlockLevel: 5,
    art: "/cards/citta_invisibile.png?v=3",
  },
  {
    id: "s10_risveglio",
    name: "L'Ultimo Risveglio",
    type: "sogno",
    cost: 5,
    power: 6,
    rarity: "leggendaria",
    text: "Pesca 1 carta.",
    flavor: "Quando il sogno finisce, inizia la vera battaglia.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 10,
    art: "/cards/ultimo_risveglio.png?v=3",
  },

  // --- FAZIONE: ECO (SMERALDO - NATURA E TEMPO) ---
  {
    id: "e1_radice",
    name: "Radice Profonda",
    type: "eco",
    cost: 2,
    power: 3,
    rarity: "comune",
    text: "Stabilità.",
    flavor: "Le fondamenta della mente sono vive.",
    effect: { kind: "none" },
    unlockLevel: 1,
    art: "/cards/radice_eco.png?v=3",
  },
  {
    id: "e2_germoglio",
    name: "Germoglio",
    type: "eco",
    cost: 1,
    power: 1,
    rarity: "comune",
    text: "Crescita.",
    flavor: "Ogni grande idea inizia con un piccolo respiro.",
    effect: { kind: "none" },
    traits: ["growth"],
    unlockLevel: 1,
    art: "/cards/germoglio_eco.png?v=3",
  },
  {
    id: "e3_foresta",
    name: "Foresta di Echi",
    type: "eco",
    cost: 5,
    power: 7,
    rarity: "epica",
    text: "+1 Potere.",
    flavor: "Le voci del passato risuonano tra le foglie d'argento.",
    effect: { kind: "buff_self", amount: 1 },
    unlockLevel: 5,
    art: "/cards/foresta_eco.png?v=3",
  },
  {
    id: "e4_pioggia_smeraldo",
    name: "Pioggia Smeraldo",
    type: "eco",
    cost: 3,
    power: 4,
    rarity: "rara",
    text: "Cura 2 HP.",
    flavor: "Un lavaggio purificatore per la coscienza stanca.",
    effect: { kind: "heal", amount: 2 },
    unlockLevel: 3,
    art: "/cards/pioggia_smeraldo.png?v=3",
  },
  {
    id: "e5_ciclo",
    name: "Il Ciclo",
    type: "eco",
    cost: 4,
    power: 6,
    rarity: "epica",
    text: "Pesca 1 carta.",
    flavor: "Ciò che è stato, sarà ancora.",
    effect: { kind: "draw", amount: 1 },
    unlockLevel: 5,
    art: "/cards/giardino_ciclo.png?v=3",
  },
  {
    id: "e6_quercia",
    name: "Quercia Antica",
    type: "eco",
    cost: 6,
    power: 10,
    rarity: "leggendaria",
    text: "Immortale.",
    flavor: "Ho visto imperi mentali sorgere e cadere.",
    effect: { kind: "none" },
    unlockLevel: 10,
    art: "/cards/quercia_antica.png?v=3",
  },
  {
    id: "e7_muschio",
    name: "Muschio Morbido",
    type: "eco",
    cost: 2,
    power: 2,
    rarity: "comune",
    text: "Protezione.",
    flavor: "Il silenzio della natura è una maschera perfetta.",
    effect: { kind: "none" },
    traits: ["protector"],
    unlockLevel: 1,
    art: "/cards/muschio_morbido.png?v=3",
  },
  {
    id: "e8_vento",
    name: "Vento del Nord",
    type: "eco",
    cost: 3,
    power: 5,
    rarity: "rara",
    text: "Spostamento.",
    flavor: "Porta via i pensieri pesanti.",
    effect: { kind: "none" },
    unlockLevel: 3,
    art: "/cards/vento_nord.png?v=3",
  },
  {
    id: "e9_pietra",
    name: "Pietra Filiale",
    type: "eco",
    cost: 7,
    power: 12,
    rarity: "leggendaria",
    text: "Alchimia.",
    flavor: "Trasformare il dolore in saggezza pura.",
    effect: { kind: "none" },
    unlockLevel: 10,
    art: "/cards/pietra_filosofale.png?v=3",
  },
  {
    id: "e10_eternita",
    name: "Eternità",
    type: "eco",
    cost: 8,
    power: 18,
    rarity: "leggendaria",
    text: "Fine del tempo.",
    flavor: "Il momento in cui tutto si ferma e tutto ha senso.",
    effect: { kind: "none" },
    traits: ["growth"],
    unlockLevel: 10,
    art: "/cards/eternita_eco.png?v=3",
  },

  // --- CARTE SPECIALI (NON COLLEZIONABILI) ---
  {
    id: "x_pensiero_intrusivo",
    name: "Pensiero Intrusivo",
    type: "oblio",
    cost: 3,
    power: -2,
    rarity: "comune",
    text: "Non puoi reprimere questo pensiero. Giocalo per rimuoverlo, sacrificando Lucidità e Potere.",
    flavor: "Un ronzio fastidioso che rifiuta di spegnersi.",
    effect: { kind: "none" },
    traits: ["immobile"],
    art: "/cards/placeholder.png",
  },
];

export const cardsById = Object.fromEntries(CARDS.map((c) => [c.id, c]));

export const TERRITORIES: {
  id: TerritoryId;
  name: string;
  rule: string;
  accent: string;
  icon: string;
}[] = [
  {
    id: "memoria",
    name: "Memoria d'Infanzia",
    rule: "A fine turno, chi controlla questo territorio pesca 1 carta.",
    accent: "var(--amber-eclipse)",
    icon: "🜂",
  },
  {
    id: "trauma",
    name: "Trauma Rimosso",
    rule: "Le carte giocate qui perdono -1 Potere.",
    accent: "var(--rose)",
    icon: "🜔",
  },
  {
    id: "sogno",
    name: "Sogno Lucido",
    rule: "Le carte giocate qui hanno +1 Potere.",
    accent: "var(--azure)",
    icon: "🜄",
  },
];
